# Generated by Django 6.0.4 on 2026-04-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_pedido_cantidad_alter_cliente_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
